version: "3"

services:

  build-go:
    build:
      context: ./golang/
      dockerfile: Dockerfile
      args:
        - CERTIFICATE_PASSWORD=$CERTIFICATE_PASSWORD
    volumes:
      - ./output/:/output/